In [1]:
import numpy as np

# Basic Array Creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3,4.5,"hello"]
a

[1, 2, 3, 4.5, 'hello']

In [5]:
np.array(a)

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [6]:
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Generation Function

In [11]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(1,5,2)

array([1., 5.])

In [20]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

# Random Generation Function

In [23]:
np.random.rand(10)

array([0.18756945, 0.37858022, 0.48270837, 0.58253616, 0.94428219,
       0.77515674, 0.65580633, 0.01735608, 0.27385929, 0.16549567])

In [28]:
np.random.randn(10) # values between -3 and 3

array([ 0.9283183 ,  2.04040135,  0.95280865, -0.12224332, -1.48481752,
        0.2966593 , -2.7500197 ,  0.83685882, -1.45809181,  2.11816135])

In [32]:
np.random.randint(6) #random integers from 0 to 6

1

In [33]:
np.random.randint(10,20,10)

array([19, 10, 11, 11, 10, 14, 19, 14, 17, 12], dtype=int32)

# Array Attributes

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)

In [40]:
arr.size # no of elements

9

In [41]:
arr.dtype

dtype('int64')

# Array Methods

In [42]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.min()

np.int64(1)

In [46]:
arr.max()

np.int64(9)

In [47]:
arr.sum()

np.int64(45)

In [50]:
np.sum(arr,axis=0) # column sum

array([12, 15, 18])

In [51]:
np.sum(arr,axis=1) # row sum

array([ 6, 15, 24])

In [52]:
arr.mean()

np.float64(5.0)

In [53]:
arr.std()

np.float64(2.581988897471611)

In [55]:
arr.argmax() # maximum element index

np.int64(8)

In [56]:
arr.argmin() # minimum element index

np.int64(0)

# Reshaping and Resizing

In [58]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [63]:
arr = arr.reshape(6,5)