In [1]:
import numpy as np

# NUMPY INDEXING AND SLICING OF VECTORS

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[4] #indexing

np.int64(15)

In [5]:
 arr[1:5] # slicing

array([12, 13, 14, 15])

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[3::2]

array([14, 16, 18, 20])

# NUMPY INDEXING AND SLICING OF MATRIX

In [13]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0]

array([1, 2, 3, 4, 5])

In [16]:
arr[0,3]

np.int64(4)

In [17]:
 arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [18]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [19]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# BOOLEAN INDEXING

In [25]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [27]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])