# ARRAY OPERATIONS

In [1]:
import numpy as np

# ARITHMETIC OPERATIONS

In [6]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [7]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1-a2

array([-5, -5, -5, -5, -5])

In [10]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [11]:
a1//a2

array([0, 0, 0, 0, 0])

In [12]:
a1 % 2 == 0

array([False,  True, False,  True, False])

In [13]:
a1 ** 2

array([ 1,  4,  9, 16, 25])

In [14]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# BROADCASTING

In [15]:
l = [10,20,30,40]
arr = np.array(l)

In [17]:
arr + 10

array([20, 30, 40, 50])

In [19]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# DEEP AND SHALLOW COPY

In [21]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
a[4:6] * 10

array([50, 60])

In [28]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
b = a     # changes
b[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# MATRIX OPEARATIONS

In [34]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [35]:
a

array([[1, 2],
       [3, 4]])

In [36]:
b

array([[5, 6],
       [7, 8]])

In [37]:
a * b

array([[ 5, 12],
       [21, 32]])

In [39]:
a @ b # matrix multiplication

array([[19, 22],
       [43, 50]])

In [40]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [42]:
a.T # transpose

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

# # Stacking Array

In [45]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [46]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# # Splitting Array

In [51]:
c = np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [55]:
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]]),
 array([[ 4],
        [ 8],
        [12],
        [16]])]

In [56]:
np.vsplit(c,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [57]:
np.vsplit(c,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]